### PR TITLE
Add Json Serialization Option

### LINKED ISSUE #17: Task: Return DTOs to Frontend as camelCase
The DTO the frontend receives is in PascalCase, allegedly. We should make it so that it's in camelCase cuz that's cooler :sunglasses: 

### Affected Functionality

Only on the frontend.

### Other Relevant Issues

N/A

### PR DESCRIPTION
**Pull request by RageCage64**
Closes #17 

Add a json serialization option to camelcase all incoming and outgoing json serialized and deserialized by the controllers.

### CODE REVIEW

**Comment by zysim** [comment]
Would we need to change anything in controller code with this change?

**Comment by zysim** [comment]
Would we need to call `services.AddMvc().AddJsonOptions()` too?

**Comment by RageCage64** [comment]
>Would we need to change anything in controller code with this change?
Nope. It uses this serialization automatically once the controllers are added to the app.

>Would we need to call services.AddMvc().AddJsonOptions() too?
Nope. This app does not use MVC, since it is only an API. If you wanted to add views for whatever reason in the future, then you would need to add it there too.

**Comment by zysim** [comment]
Oh yeah, true, this isn't an MVC project lmao. Aight sweet I'll fix the merge conflict and merge this.

**Review by zysim — APPROVED** [review]

**Pull request merged**
